- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install useful packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - vim
    - git
    - firewalld

- name: Install fail2ban
  yum:
    name: epel-release
    state: present

- name: Install fail2ban from EPEL
  yum:
    name: fail2ban
    state: present

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

