- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx to use /var/www/html
  copy:
    dest: /etc/nginx/conf.d/default.conf
    content: |
      server {
          listen       80;
          server_name  localhost;

          location / {
              root   /var/www/html;
              index  index.html index.htm;
          }

          error_page 404 /404.html;
              location = /40x.html {
          }

          error_page 500 502 503 504 /50x.html;
              location = /50x.html {
          }
      }
  notify: reload nginx

